# meta-visionfive2-demo — the demo-specific layer on top of meta-riscv + poky.
# Depends on riscv, core; priority above meta-riscv (6).

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "visionfive2-demo"
BBFILE_PATTERN_visionfive2-demo = "^${LAYERDIR}/"
BBFILE_PRIORITY_visionfive2-demo = "10"

LAYERDEPENDS_visionfive2-demo = "core riscv-layer"
LAYERSERIES_COMPAT_visionfive2-demo = "wrynose"
